/**
 *
 *  ChequeItems.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace expense_db
{
class Categories;
class Cheques;

class ChequeItems
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _cheque_id;
        static const std::string _category_id;
        static const std::string _product_name;
        static const std::string _quantity;
        static const std::string _unit_price;
        static const std::string _total_price;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit ChequeItems(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit ChequeItems(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    ChequeItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    ChequeItems() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column cheque_id  */
    ///Get the value of the column cheque_id, returns the default value if the column is null
    const int64_t &getValueOfChequeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getChequeId() const noexcept;
    ///Set the value of the column cheque_id
    void setChequeId(const int64_t &pChequeId) noexcept;

    /**  For column category_id  */
    ///Get the value of the column category_id, returns the default value if the column is null
    const int32_t &getValueOfCategoryId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getCategoryId() const noexcept;
    ///Set the value of the column category_id
    void setCategoryId(const int32_t &pCategoryId) noexcept;
    void setCategoryIdToNull() noexcept;

    /**  For column product_name  */
    ///Get the value of the column product_name, returns the default value if the column is null
    const std::string &getValueOfProductName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProductName() const noexcept;
    ///Set the value of the column product_name
    void setProductName(const std::string &pProductName) noexcept;
    void setProductName(std::string &&pProductName) noexcept;

    /**  For column quantity  */
    ///Get the value of the column quantity, returns the default value if the column is null
    const std::string &getValueOfQuantity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getQuantity() const noexcept;
    ///Set the value of the column quantity
    void setQuantity(const std::string &pQuantity) noexcept;
    void setQuantity(std::string &&pQuantity) noexcept;

    /**  For column unit_price  */
    ///Get the value of the column unit_price, returns the default value if the column is null
    const std::string &getValueOfUnitPrice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUnitPrice() const noexcept;
    ///Set the value of the column unit_price
    void setUnitPrice(const std::string &pUnitPrice) noexcept;
    void setUnitPrice(std::string &&pUnitPrice) noexcept;

    /**  For column total_price  */
    ///Get the value of the column total_price, returns the default value if the column is null
    const std::string &getValueOfTotalPrice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTotalPrice() const noexcept;
    ///Set the value of the column total_price
    void setTotalPrice(const std::string &pTotalPrice) noexcept;
    void setTotalPrice(std::string &&pTotalPrice) noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Cheques getCheques(const drogon::orm::DbClientPtr &clientPtr) const;
    void getCheques(const drogon::orm::DbClientPtr &clientPtr,
                    const std::function<void(Cheques)> &rcb,
                    const drogon::orm::ExceptionCallback &ecb) const;
    Categories getCategories(const drogon::orm::DbClientPtr &clientPtr) const;
    void getCategories(const drogon::orm::DbClientPtr &clientPtr,
                       const std::function<void(Categories)> &rcb,
                       const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<ChequeItems>;
    friend drogon::orm::BaseBuilder<ChequeItems, true, true>;
    friend drogon::orm::BaseBuilder<ChequeItems, true, false>;
    friend drogon::orm::BaseBuilder<ChequeItems, false, true>;
    friend drogon::orm::BaseBuilder<ChequeItems, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<ChequeItems>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> chequeId_;
    std::shared_ptr<int32_t> categoryId_;
    std::shared_ptr<std::string> productName_;
    std::shared_ptr<std::string> quantity_;
    std::shared_ptr<std::string> unitPrice_;
    std::shared_ptr<std::string> totalPrice_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "cheque_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "category_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "product_name,";
            ++parametersCount;
        }
        sql += "quantity,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "unit_price,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "total_price,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace expense_db
} // namespace drogon_model
