/**
 *
 *  ChequeItems.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ChequeItems.h"
#include "Categories.h"
#include "Cheques.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::expense_db;

const std::string ChequeItems::Cols::_id = "\"id\"";
const std::string ChequeItems::Cols::_cheque_id = "\"cheque_id\"";
const std::string ChequeItems::Cols::_category_id = "\"category_id\"";
const std::string ChequeItems::Cols::_product_name = "\"product_name\"";
const std::string ChequeItems::Cols::_quantity = "\"quantity\"";
const std::string ChequeItems::Cols::_unit_price = "\"unit_price\"";
const std::string ChequeItems::Cols::_total_price = "\"total_price\"";
const std::string ChequeItems::primaryKeyName = "id";
const bool ChequeItems::hasPrimaryKey = true;
const std::string ChequeItems::tableName = "\"cheque_items\"";

const std::vector<typename ChequeItems::MetaData> ChequeItems::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"cheque_id","int64_t","bigint",8,0,0,1},
{"category_id","int32_t","integer",4,0,0,0},
{"product_name","std::string","character varying",255,0,0,1},
{"quantity","std::string","numeric",0,0,0,1},
{"unit_price","std::string","numeric",0,0,0,1},
{"total_price","std::string","numeric",0,0,0,1}
};
const std::string &ChequeItems::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ChequeItems::ChequeItems(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["cheque_id"].isNull())
        {
            chequeId_=std::make_shared<int64_t>(r["cheque_id"].as<int64_t>());
        }
        if(!r["category_id"].isNull())
        {
            categoryId_=std::make_shared<int32_t>(r["category_id"].as<int32_t>());
        }
        if(!r["product_name"].isNull())
        {
            productName_=std::make_shared<std::string>(r["product_name"].as<std::string>());
        }
        if(!r["quantity"].isNull())
        {
            quantity_=std::make_shared<std::string>(r["quantity"].as<std::string>());
        }
        if(!r["unit_price"].isNull())
        {
            unitPrice_=std::make_shared<std::string>(r["unit_price"].as<std::string>());
        }
        if(!r["total_price"].isNull())
        {
            totalPrice_=std::make_shared<std::string>(r["total_price"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            chequeId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            categoryId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            productName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            quantity_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            unitPrice_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            totalPrice_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ChequeItems::ChequeItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            chequeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            categoryId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            productName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            quantity_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            unitPrice_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            totalPrice_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

ChequeItems::ChequeItems(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("cheque_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["cheque_id"].isNull())
        {
            chequeId_=std::make_shared<int64_t>((int64_t)pJson["cheque_id"].asInt64());
        }
    }
    if(pJson.isMember("category_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["category_id"].isNull())
        {
            categoryId_=std::make_shared<int32_t>((int32_t)pJson["category_id"].asInt64());
        }
    }
    if(pJson.isMember("product_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["product_name"].isNull())
        {
            productName_=std::make_shared<std::string>(pJson["product_name"].asString());
        }
    }
    if(pJson.isMember("quantity"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["quantity"].isNull())
        {
            quantity_=std::make_shared<std::string>(pJson["quantity"].asString());
        }
    }
    if(pJson.isMember("unit_price"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["unit_price"].isNull())
        {
            unitPrice_=std::make_shared<std::string>(pJson["unit_price"].asString());
        }
    }
    if(pJson.isMember("total_price"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["total_price"].isNull())
        {
            totalPrice_=std::make_shared<std::string>(pJson["total_price"].asString());
        }
    }
}

void ChequeItems::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            chequeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            categoryId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            productName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            quantity_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            unitPrice_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            totalPrice_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

void ChequeItems::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("cheque_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["cheque_id"].isNull())
        {
            chequeId_=std::make_shared<int64_t>((int64_t)pJson["cheque_id"].asInt64());
        }
    }
    if(pJson.isMember("category_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["category_id"].isNull())
        {
            categoryId_=std::make_shared<int32_t>((int32_t)pJson["category_id"].asInt64());
        }
    }
    if(pJson.isMember("product_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["product_name"].isNull())
        {
            productName_=std::make_shared<std::string>(pJson["product_name"].asString());
        }
    }
    if(pJson.isMember("quantity"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["quantity"].isNull())
        {
            quantity_=std::make_shared<std::string>(pJson["quantity"].asString());
        }
    }
    if(pJson.isMember("unit_price"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["unit_price"].isNull())
        {
            unitPrice_=std::make_shared<std::string>(pJson["unit_price"].asString());
        }
    }
    if(pJson.isMember("total_price"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["total_price"].isNull())
        {
            totalPrice_=std::make_shared<std::string>(pJson["total_price"].asString());
        }
    }
}

const int64_t &ChequeItems::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ChequeItems::getId() const noexcept
{
    return id_;
}
void ChequeItems::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename ChequeItems::PrimaryKeyType & ChequeItems::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &ChequeItems::getValueOfChequeId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(chequeId_)
        return *chequeId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ChequeItems::getChequeId() const noexcept
{
    return chequeId_;
}
void ChequeItems::setChequeId(const int64_t &pChequeId) noexcept
{
    chequeId_ = std::make_shared<int64_t>(pChequeId);
    dirtyFlag_[1] = true;
}

const int32_t &ChequeItems::getValueOfCategoryId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(categoryId_)
        return *categoryId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ChequeItems::getCategoryId() const noexcept
{
    return categoryId_;
}
void ChequeItems::setCategoryId(const int32_t &pCategoryId) noexcept
{
    categoryId_ = std::make_shared<int32_t>(pCategoryId);
    dirtyFlag_[2] = true;
}
void ChequeItems::setCategoryIdToNull() noexcept
{
    categoryId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &ChequeItems::getValueOfProductName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(productName_)
        return *productName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ChequeItems::getProductName() const noexcept
{
    return productName_;
}
void ChequeItems::setProductName(const std::string &pProductName) noexcept
{
    productName_ = std::make_shared<std::string>(pProductName);
    dirtyFlag_[3] = true;
}
void ChequeItems::setProductName(std::string &&pProductName) noexcept
{
    productName_ = std::make_shared<std::string>(std::move(pProductName));
    dirtyFlag_[3] = true;
}

const std::string &ChequeItems::getValueOfQuantity() const noexcept
{
    static const std::string defaultValue = std::string();
    if(quantity_)
        return *quantity_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ChequeItems::getQuantity() const noexcept
{
    return quantity_;
}
void ChequeItems::setQuantity(const std::string &pQuantity) noexcept
{
    quantity_ = std::make_shared<std::string>(pQuantity);
    dirtyFlag_[4] = true;
}
void ChequeItems::setQuantity(std::string &&pQuantity) noexcept
{
    quantity_ = std::make_shared<std::string>(std::move(pQuantity));
    dirtyFlag_[4] = true;
}

const std::string &ChequeItems::getValueOfUnitPrice() const noexcept
{
    static const std::string defaultValue = std::string();
    if(unitPrice_)
        return *unitPrice_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ChequeItems::getUnitPrice() const noexcept
{
    return unitPrice_;
}
void ChequeItems::setUnitPrice(const std::string &pUnitPrice) noexcept
{
    unitPrice_ = std::make_shared<std::string>(pUnitPrice);
    dirtyFlag_[5] = true;
}
void ChequeItems::setUnitPrice(std::string &&pUnitPrice) noexcept
{
    unitPrice_ = std::make_shared<std::string>(std::move(pUnitPrice));
    dirtyFlag_[5] = true;
}

const std::string &ChequeItems::getValueOfTotalPrice() const noexcept
{
    static const std::string defaultValue = std::string();
    if(totalPrice_)
        return *totalPrice_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ChequeItems::getTotalPrice() const noexcept
{
    return totalPrice_;
}
void ChequeItems::setTotalPrice(const std::string &pTotalPrice) noexcept
{
    totalPrice_ = std::make_shared<std::string>(pTotalPrice);
    dirtyFlag_[6] = true;
}
void ChequeItems::setTotalPrice(std::string &&pTotalPrice) noexcept
{
    totalPrice_ = std::make_shared<std::string>(std::move(pTotalPrice));
    dirtyFlag_[6] = true;
}

void ChequeItems::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ChequeItems::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "cheque_id",
        "category_id",
        "product_name",
        "quantity",
        "unit_price",
        "total_price"
    };
    return inCols;
}

void ChequeItems::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChequeId())
        {
            binder << getValueOfChequeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCategoryId())
        {
            binder << getValueOfCategoryId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getProductName())
        {
            binder << getValueOfProductName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getQuantity())
        {
            binder << getValueOfQuantity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUnitPrice())
        {
            binder << getValueOfUnitPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTotalPrice())
        {
            binder << getValueOfTotalPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ChequeItems::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void ChequeItems::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChequeId())
        {
            binder << getValueOfChequeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCategoryId())
        {
            binder << getValueOfCategoryId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getProductName())
        {
            binder << getValueOfProductName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getQuantity())
        {
            binder << getValueOfQuantity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUnitPrice())
        {
            binder << getValueOfUnitPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTotalPrice())
        {
            binder << getValueOfTotalPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ChequeItems::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChequeId())
    {
        ret["cheque_id"]=(Json::Int64)getValueOfChequeId();
    }
    else
    {
        ret["cheque_id"]=Json::Value();
    }
    if(getCategoryId())
    {
        ret["category_id"]=getValueOfCategoryId();
    }
    else
    {
        ret["category_id"]=Json::Value();
    }
    if(getProductName())
    {
        ret["product_name"]=getValueOfProductName();
    }
    else
    {
        ret["product_name"]=Json::Value();
    }
    if(getQuantity())
    {
        ret["quantity"]=getValueOfQuantity();
    }
    else
    {
        ret["quantity"]=Json::Value();
    }
    if(getUnitPrice())
    {
        ret["unit_price"]=getValueOfUnitPrice();
    }
    else
    {
        ret["unit_price"]=Json::Value();
    }
    if(getTotalPrice())
    {
        ret["total_price"]=getValueOfTotalPrice();
    }
    else
    {
        ret["total_price"]=Json::Value();
    }
    return ret;
}

std::string ChequeItems::toString() const
{
    return toJson().toStyledString();
}

Json::Value ChequeItems::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getChequeId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfChequeId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getCategoryId())
            {
                ret[pMasqueradingVector[2]]=getValueOfCategoryId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getProductName())
            {
                ret[pMasqueradingVector[3]]=getValueOfProductName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getQuantity())
            {
                ret[pMasqueradingVector[4]]=getValueOfQuantity();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUnitPrice())
            {
                ret[pMasqueradingVector[5]]=getValueOfUnitPrice();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getTotalPrice())
            {
                ret[pMasqueradingVector[6]]=getValueOfTotalPrice();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChequeId())
    {
        ret["cheque_id"]=(Json::Int64)getValueOfChequeId();
    }
    else
    {
        ret["cheque_id"]=Json::Value();
    }
    if(getCategoryId())
    {
        ret["category_id"]=getValueOfCategoryId();
    }
    else
    {
        ret["category_id"]=Json::Value();
    }
    if(getProductName())
    {
        ret["product_name"]=getValueOfProductName();
    }
    else
    {
        ret["product_name"]=Json::Value();
    }
    if(getQuantity())
    {
        ret["quantity"]=getValueOfQuantity();
    }
    else
    {
        ret["quantity"]=Json::Value();
    }
    if(getUnitPrice())
    {
        ret["unit_price"]=getValueOfUnitPrice();
    }
    else
    {
        ret["unit_price"]=Json::Value();
    }
    if(getTotalPrice())
    {
        ret["total_price"]=getValueOfTotalPrice();
    }
    else
    {
        ret["total_price"]=Json::Value();
    }
    return ret;
}

bool ChequeItems::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("cheque_id"))
    {
        if(!validJsonOfField(1, "cheque_id", pJson["cheque_id"], err, true))
            return false;
    }
    else
    {
        err="The cheque_id column cannot be null";
        return false;
    }
    if(pJson.isMember("category_id"))
    {
        if(!validJsonOfField(2, "category_id", pJson["category_id"], err, true))
            return false;
    }
    if(pJson.isMember("product_name"))
    {
        if(!validJsonOfField(3, "product_name", pJson["product_name"], err, true))
            return false;
    }
    else
    {
        err="The product_name column cannot be null";
        return false;
    }
    if(pJson.isMember("quantity"))
    {
        if(!validJsonOfField(4, "quantity", pJson["quantity"], err, true))
            return false;
    }
    if(pJson.isMember("unit_price"))
    {
        if(!validJsonOfField(5, "unit_price", pJson["unit_price"], err, true))
            return false;
    }
    else
    {
        err="The unit_price column cannot be null";
        return false;
    }
    if(pJson.isMember("total_price"))
    {
        if(!validJsonOfField(6, "total_price", pJson["total_price"], err, true))
            return false;
    }
    else
    {
        err="The total_price column cannot be null";
        return false;
    }
    return true;
}
bool ChequeItems::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ChequeItems::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("cheque_id"))
    {
        if(!validJsonOfField(1, "cheque_id", pJson["cheque_id"], err, false))
            return false;
    }
    if(pJson.isMember("category_id"))
    {
        if(!validJsonOfField(2, "category_id", pJson["category_id"], err, false))
            return false;
    }
    if(pJson.isMember("product_name"))
    {
        if(!validJsonOfField(3, "product_name", pJson["product_name"], err, false))
            return false;
    }
    if(pJson.isMember("quantity"))
    {
        if(!validJsonOfField(4, "quantity", pJson["quantity"], err, false))
            return false;
    }
    if(pJson.isMember("unit_price"))
    {
        if(!validJsonOfField(5, "unit_price", pJson["unit_price"], err, false))
            return false;
    }
    if(pJson.isMember("total_price"))
    {
        if(!validJsonOfField(6, "total_price", pJson["total_price"], err, false))
            return false;
    }
    return true;
}
bool ChequeItems::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ChequeItems::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Cheques ChequeItems::getCheques(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from cheques where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *chequeId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Cheques(r[0]);
}

void ChequeItems::getCheques(const DbClientPtr &clientPtr,
                             const std::function<void(Cheques)> &rcb,
                             const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from cheques where id = $1";
    *clientPtr << sql
               << *chequeId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Cheques(r[0]));
                    }
               }
               >> ecb;
}
Categories ChequeItems::getCategories(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from categories where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *categoryId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Categories(r[0]);
}

void ChequeItems::getCategories(const DbClientPtr &clientPtr,
                                const std::function<void(Categories)> &rcb,
                                const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from categories where id = $1";
    *clientPtr << sql
               << *categoryId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Categories(r[0]));
                    }
               }
               >> ecb;
}
