name: Calculator Google Tests

on:
  push:
    paths:
      - 'Calculator/*'
      - 'Calculator/'
      - 'Calculator'

jobs:
  build:
    runs-on: ubuntu-20.04
    
    env:
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake 
      working-directory: Calculator/Tests
      run: cmake . -B build

    - name: Build Tests
      working-directory: Calculator/Tests
      run: cmake --build build

    - name: Test Results
      working-directory: Calculator/Tests/build
      run: ctest
