name: Running Google Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: URLParser/Tests
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: URLParser/Tests/build
      run: ctest
