name: Linear Algebra Google Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    env:
      CXX: g++-10.3.0

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake 
      working-directory: LinearAlgebra/Tester
      run: cmake . -B build

    - name: Build Tests
      working-directory: LinearAlgebra/Tester
      run: cmake --build build

    - name: Test Results
      working-directory: LinearAlgebra/Tester/build
      run: ctest
