name: CI CMake

env:
  CMAKE_GENERATOR: MinGW Makefiles

on:
  push:
  - "**/CMakeLists.txt"
  - "**.cmake"
  - "**.cmake.in"
  - "**.cpp"
  - "**.hpp"
  - "**.h.in"
  - ".github/workflows/linear_algebra.yml"
  pull_request:

jobs:

  windows:
    runs-on: windows-latest
    name: CMake build on Windows
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-msmpi

    - name: CMake configure
      run: cmake -B build -G "MinGW Makefiles"

    - name: CMake build
      run: cmake --build build

    - name: CMake self-tests
      run: cd build && ctest